load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "gtest",
    url = "https://github.com/google/googletest/archive/release-1.10.0.zip",
    sha256 = "94c634d499558a76fa649edb13721dce6e98fb1e7018dfaeba3cd7a083945e91",
    build_file = "@//:gtest.BUILD",
    strip_prefix = "googletest-release-1.10.0",
)

http_archive(
    name = "xerces",
    url = "https://dlcdn.apache.org//xerces/c/3/sources/xerces-c-3.2.3.zip",
    sha256 = "4a3a23ed859cff886e50ee8b30e3223c603fbcad86d1ba5a11f29da692b825ce",
)
